// libs/examples/src/lib/python-tutor/global-frame.tsx
import { Align, Distribute, Group, Rect, Ref } from '@bluefishjs/bluefish';
import { useId } from 'react';
import Variable from './variable';

export type GlobalFrameProps = {
  variables: { name: string; value: string }[];
};

export function GlobalFrame({ variables }: GlobalFrameProps) {
  const id = useId();

  // Font declaration
  const fontFamily = 'Andale mono, monospace';

  return (
    <Group id={`group${id}`}>
      {/* Global Frame and relevant text */}
      <Rect id={`frame${id}`} height={300} width={200} fill={'#e2ebf6'} />
      <Rect id={`frameBorder${id}`} height={300} width={5} fill={'#a6b3b6'} />
      {/* <Text
        name={opIdLabel}
        contents={'Global Frame'}
        fontSize={'24px'}
        fontFamily={fontFamily}
        fill={'black'}
      /> */}
      {/* <Rect id={`global frame ${id}`} width={10} height={10} fill="blue" /> */}
      <Align x={0} y={0} id={`align1${id}`} alignment="topCenter">
        {/* <Ref id={`ref1${id}`} refId={`global frame ${id}`} /> */}
        <Rect id={`global frame ${id}`} width={10} height={10} fill="blue" />
        <Ref id={`ref2${id}`} refId={`frame${id}`} />
      </Align>
      <Distribute id={`distribute1${id}`} direction="vertical" spacing={10}>
        <Ref id={`ref3${id}`} refId={`global frame ${id}`} />
        <Align id={`frameVariables${id}`} alignment="right">
          {variables.map((variable, i) => (
            <Variable
              id={`variable${i}${id}`}
              name={variable.name}
              value={variable.value}
            />
          ))}
        </Align>
        <Distribute id={`distribute2${id}`} direction="vertical" spacing={10}>
          {variables.map((variable, i: number) => (
            <Ref id={`ref4${i}${id}`} refId={`variable${i}${id}`} />
          ))}
        </Distribute>
      </Distribute>
      <Align id={`align3${id}`} alignment="right">
        <Ref id={`ref5${id}`} refId={`frameVariables${id}`} />
        <Ref id={`ref6${id}`} refId={`global frame ${id}`} />
      </Align>
      <Align id={`align4${id}`} alignment="centerLeft">
        <Ref id={`ref7${id}`} refId={`frameBorder${id}`} />
        <Ref id={`ref8${id}`} refId={`frame${id}`} />
      </Align>
    </Group>
  );
}

// packages/bluefish-solid/src/python-tutor/global-frame.tsx
import { For, createUniqueId } from "solid-js";
import { Id } from "../scenegraph";
import Rect from "../rect";
import Group from "../group";
import Align from "../align";
import Ref from "../ref";
import { StackSlot } from "./stack-slot";
import Distribute from "../distribute";
import Text from "../text";
import { Value } from "./types";
import { createName } from "../createName";
import { StackV } from "../stackv";
import withBluefish from "../withBluefish";

export type GlobalFrameProps = {
  name?: Id;
  variables: { variable: string; value: Value }[];
};

export const GlobalFrame = withBluefish((props: GlobalFrameProps) => {
  const frameName = createName("frame");
  const frameBorderName = createName("frameBorder");
  const labelName = createName("label");
  const frameVariablesName = createName("frameVariables");
  const stackSlotNames = props.variables.map((_, i) =>
    createName(`stackSlot-${i}`)
  );

  // Font declaration
  const fontFamily = "Andale mono, monospace";

  return (
    <Group
      rels={() => (
        <>
          <Align alignment="topCenter">
            <Ref select={labelName} />
            <Ref select={frameName} />
          </Align>
          <Align alignment="centerLeft">
            <Ref select={frameBorderName} />
            <Ref select={frameName} />
          </Align>
          <StackV alignment="right" spacing={10}>
            <Ref select={labelName} />
            <Ref select={frameVariablesName} />
          </StackV>
        </>
      )}
    >
      {/* Global Frame and relevant text */}
      <Rect name={frameName} height={300} width={200} fill={"#e2ebf6"} />
      <Rect name={frameBorderName} height={300} width={5} fill={"#a6b3b6"} />
      {/* TODO: there is a bug where the text is showing up lower than I expect it to... */}
      <Text
        name={labelName}
        font-size={"24px"}
        font-family={fontFamily}
        fill={"black"}
      >
        Global Frame
      </Text>
      <StackV name={frameVariablesName} alignment="right" spacing={10}>
        <For each={props.variables}>
          {(variable, i) => (
            <StackSlot
              name={stackSlotNames[i()]}
              variable={variable.variable}
              value={variable.value as any}
            />
          )}
        </For>
      </StackV>
    </Group>
  );
});

export default GlobalFrame;
